/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconButton: typeof import('./src/components/editor/IconButton/IconButton.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    MainContent: typeof import('./src/components/layout/Content/MainContent.vue')['default']
    Popover: typeof import('./src/components/common/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderBar: typeof import('./src/components/layout/SiderBar/SiderBar.vue')['default']
    Slider: typeof import('./src/components/editor/Slider/Slider.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    ViewFooter: typeof import('./src/components/layout/Footer/ViewFooter.vue')['default']
    ViewHeader: typeof import('./src/components/layout/Header/ViewHeader.vue')['default']
  }
}
